  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-html
spec:
  selector:
    matchLabels:
      app: web2-html
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web2-html
    spec:
      containers:
      - name: web2-html
        image: sitemay/denemerepo:v$DOCKER_BUILD_NUMBER
        ports:
        - containerPort: 80
