apiVersion: v1
kind: Service
metadata:
  name: web2-html
  namespace: default
spec:
  selector:
    app: web2-html
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
